Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class MainController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Projects()
        {
            return View();
        }

        public ActionResult TemperatureChecker()
        {
            return View();
        }

        public ActionResult NumberGuessing()
        {
            return View();
        }
    }
}

Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class PeopleController : Controller
    {
        public ActionResult Index()
        {
            if (Person.PeopleList == null)
                Person.GenerateList();

            return View(new Person());
        }

        public ActionResult Add(string name, string phone, string city)
        {
            if (Person.PeopleList != null)
            {
                if(name.Length < 2 || city.Length < 2) return new HttpStatusCodeResult(400);
                Person.PeopleList.Add(new Person(name, phone, city));
                return View("Index", new Person());
            }
            return new HttpStatusCodeResult(401);
        }

        public ActionResult Delete(int ID)
        {
            if (Person.PeopleList != null)
            {
                Person found = Person.PeopleList.FirstOrDefault(item => item.ID == ID);
                if (found != null)
                {
                    Person.PeopleList.Remove(found);
                }
                return View("Index", new Person());
            }
            return new HttpStatusCodeResult(401);
        }
    }
}

Controllers/PeopleV2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class PeopleV2Controller : Controller
    {
        public ActionResult Index()
        {
            if (Person.PeopleList == null)
                Person.GenerateList();

            return View(Person.PeopleList);
        }

        public ActionResult Add(string name, string phone, string city)
        {
            if (Person.PeopleList != null)
            {
                if(name.Length < 2 || city.Length < 2) return new HttpStatusCodeResult(400);
                Person.PeopleList.Add(new Person(name, phone, city));
                return View("Index", Person.PeopleList);
            }
            return new HttpStatusCodeResult(401);
        }

        public ActionResult Delete(int ID)
        {
            if (Person.PeopleList != null)
            {
                Person found = Person.PeopleList.FirstOrDefault(item => item.ID == ID);
                if (found != null)
                {
                    Person.PeopleList.Remove(found);
                }
                return View("Index", Person.PeopleList);
            }
            return new HttpStatusCodeResult(401);
        }

        public PartialViewResult ShowPerson(Person person)
        {
            return PartialView("_PartialPerson", person);
        }
    }
}

Controllers/PeopleWithAjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class PeopleWithAjaxController : Controller
    {
        public ActionResult Index(string search = "", bool caseSensitive = false)
        {
            if (Person.PeopleList == null)
                Person.GenerateList();

            List<Person> model = Person.FilterList(Person.PeopleList, search, caseSensitive);

            if(Request.IsAjaxRequest())
            {
                return PartialView("_List", model);
            }

            return View(model);
        }

        public ActionResult Add(string name, string phone, string city)
        {
            if (Person.PeopleList != null)
            {
                if(name.Length < 2 || city.Length < 2) return new HttpStatusCodeResult(400);
                Person.PeopleList.Add(new Person(name, phone, city));
                return PartialView("_List", Person.PeopleList);
            }
            return new HttpStatusCodeResult(401);
        }

        public ActionResult Delete(int ID)
        {
            if (Person.PeopleList != null)
            {
                Person found = Person.PeopleList.FirstOrDefault(item => item.ID == ID);
                if (found != null)
                {
                    Person.PeopleList.Remove(found);
                }
                return PartialView("_List", Person.PeopleList);
            }
            return new HttpStatusCodeResult(401);
        }

        public ActionResult EditStart(int ID)
        {
            if (Person.PeopleList != null)
            {
                Person found = Person.PeopleList.FirstOrDefault(item => item.ID == ID);
                if (found != null)
                {
                    return PartialView("_PartialPersonEdit", found);
                }
                return new HttpStatusCodeResult(404);
            }
            return new HttpStatusCodeResult(401);
        }

        public ActionResult Edit(Person edited)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(400);
            }
            if (Person.PeopleList != null)
            {
                Person found = Person.PeopleList.FirstOrDefault(item => item.ID == edited.ID);
                if (found != null)
                {
                    found = edited;
                    return PartialView("_PartialPerson", found);
                }
                return new HttpStatusCodeResult(404);
            }
            return new HttpStatusCodeResult(401);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @using System.Web.Optimization
    @Styles.Render("~/Content/css")
</head>
<body class="bg-secondary text-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <div class="navbar-brand">
                <img src="https://v4-alpha.getbootstrap.com/assets/brand/bootstrap-solid.svg" />
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("About", "Index", "Main", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Contact", "Contact", "Main", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Projects", "Projects", "Main", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Temp Checker", "", "FeverCheck", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Number Guessing", "", "GuessingGame", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("People List", "Index", "People", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("People List 2", "Index", "PeopleV2", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("People List 3", "Index", "PeopleWithAjax", null, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container" id="main-container">
        @RenderBody()
    </div>
    <footer class="fixed-bottom bg-dark text-light">@DateTime.Now Carl König</footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>